import { mkdtemp } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { buildUserMessage, callModel, createAiConfig, resolveProposal, type AiConfig, type AiContext } from '../server/ai';
import { createTemplateStore } from '../server/templateStore';
import { createProxyConfig, handleTunarrApi, type ProxyConfig, type ProxyRequest } from '../server/tunarrProxy';

const SHOW = '0e2d2a41-5f2f-4a7e-9d3a-2b1f0c9e8d7a';
const COLLECTION = '1e2d2a41-5f2f-4a7e-9d3a-2b1f0c9e8d7b';
const ADS = '2e2d2a41-5f2f-4a7e-9d3a-2b1f0c9e8d7c';

const context: AiContext = {
  shows: [{ id: SHOW, title: 'Sailor Moon', year: 1992, genres: ['Anime'], episodes: 200, mediaSourceId: 'ms', libraryId: 'lib' }],
  movies: { count: 1, sample: ['Ponyo (2008) [Animation]'] },
  smartCollections: [{ id: COLLECTION, name: 'Ghibli' }],
  customShows: [],
  fillerLists: [{ id: ADS, name: 'Commercials 90s' }],
};

const proposal = {
  name: 'Saturday morning',
  description: 'Cartoons and anime.',
  inspiredBy: '',
  region: 'Anywhere',
  notes: 'Your library has no live-action kids shows.',
  padMinutes: 30,
  latenessMinutes: 15,
  ads: { label: 'Toy commercials', breakEveryMin: 7, breakMin: 2, maxBreaks: 3, commercialsAt: ['mid', 'post'], promosAt: ['pre'] },
  roles: [
    { id: 'anime', label: 'Anime', order: 'next', source: { kind: 'show', id: SHOW } },
    { id: 'films', label: 'Films', order: 'shuffle', source: { kind: 'smartCollection', id: COLLECTION } },
    { id: 'made-up', label: 'Made up', order: 'shuffle', source: { kind: 'show', id: 'not-in-catalog' } },
    { id: 'cartoons', label: 'Cartoons', order: 'shuffle', source: { kind: 'suggest' }, suggest: { match: 'all', rules: [{ field: 'type', op: 'is', values: ['episode'] }, { field: 'show_genre', op: 'is', values: ['Animation'] }] } },
    { id: 'bad-rules', label: 'Bad rules', order: 'shuffle', source: { kind: 'suggest' }, suggest: { match: 'all', rules: [{ field: 'password', op: 'is', values: ['x'] }] } },
  ],
  days: { all: [{ start: '07:00', role: 'cartoons' }, { start: '09:00', role: 'anime', ads: 'heavy' }, { start: '12:00', role: 'films', ads: 'none' }, { start: '15:00', role: 'made-up' }, { start: '18:00', role: 'bad-rules' }] },
  lists: { commercialsListId: ADS, promosListId: 'unknown' },
};

describe('AI configuration', () => {
  it('is off until a provider is set up', () => {
    expect(createAiConfig({})).toHaveProperty('off');
    expect(createAiConfig({ LINEUP_AI_PROVIDER: 'anthropic' })).toEqual({ off: expect.stringMatching(/API_KEY/) });
    expect(createAiConfig({ ANTHROPIC_API_KEY: 'sk-ant' })).toMatchObject({ provider: 'anthropic', model: 'claude-sonnet-5-5', baseUrl: 'https://api.anthropic.com', apiKey: 'sk-ant' });
    expect(createAiConfig({ LINEUP_AI_BASE_URL: 'http://ollama:11434/v1/' })).toEqual({ off: expect.stringMatching(/LINEUP_AI_MODEL/) });
    expect(createAiConfig({ LINEUP_AI_BASE_URL: 'http://ollama:11434/v1/', LINEUP_AI_MODEL: 'llama3.1' })).toMatchObject({ provider: 'openai', baseUrl: 'http://ollama:11434/v1', apiKey: undefined });
    expect(createAiConfig({ LINEUP_AI_PROVIDER: 'openai', LINEUP_AI_BASE_URL: 'file:///etc', LINEUP_AI_MODEL: 'x' })).toHaveProperty('off');
  });
});

describe('AI proposals', () => {
  it('maps roles to real catalog items and drops what it can’t use', () => {
    const resolved = resolveProposal(proposal, context, 'ai-test');
    if ('error' in resolved) throw new Error(resolved.error);
    const { template, lists, notes } = resolved;
    expect(template).toMatchObject({ id: 'ai-test', name: 'Saturday morning', inspiredBy: 'Generated by AI from your prompt', padMs: 30 * 60_000, latenessMs: 15 * 60_000 });
    expect(template.days).toEqual({ all: [['07:00', 'cartoons'], ['09:00', 'anime', 'heavy'], ['12:00', 'films', 'none'], ['15:00', 'made-up'], ['18:00', 'bad-rules']] });
    expect(template.ads.midRoll).toEqual({ everyMin: 7, breakMin: 2, maxBreaks: 3, minProgramMin: 15 });
    expect(template.defaults!.anime).toMatchObject({ key: `show:${SHOW}`, label: 'Sailor Moon', template: { type: 'show', showId: SHOW, show: { mediaSourceId: 'ms', libraryId: 'lib' } } });
    expect(template.defaults!.films).toMatchObject({ key: `smart-collection:${COLLECTION}` });
    expect(template.defaults!['made-up']).toBeUndefined();
    expect(template.roles.find((role) => role.id === 'cartoons')!.suggest).toBeDefined();
    expect(template.roles.find((role) => role.id === 'bad-rules')!.suggest).toBeUndefined();
    expect(lists).toEqual({ commercials: ADS });
    expect(notes).toMatch(/no live-action.*Couldn't match Made up/);
  });

  it('refuses proposals that aren’t a usable plan', () => {
    expect(resolveProposal({ ...proposal, days: { all: [{ start: '7am', role: 'anime' }] } }, context, 'ai-x')).toHaveProperty('error');
    expect(resolveProposal('nope', context, 'ai-x')).toHaveProperty('error');
  });

  it('marks the catalog as data in the prompt', () => {
    const message = buildUserMessage('cartoons', context);
    expect(message).toContain(`${SHOW} | Sailor Moon | 1992 | Anime | 200`);
    expect(message).toContain(`${ADS} | Commercials 90s`);
  });
});

describe('AI providers', () => {
  const capture = (reply: unknown, status = 200) => {
    const calls: Array<{ url: string; headers: Record<string, string>; body: Record<string, unknown> }> = [];
    const fetchImpl = (async (url: string, init: RequestInit) => {
      calls.push({ url, headers: init.headers as Record<string, string>, body: JSON.parse(String(init.body)) });
      return new Response(JSON.stringify(reply), { status });
    }) as unknown as typeof fetch;
    return { calls, fetchImpl };
  };

  it('forces the tool on Anthropic’s Messages API', async () => {
    const { calls, fetchImpl } = capture({ content: [{ type: 'text', text: 'Here you go' }, { type: 'tool_use', name: 'propose_schedule', input: { name: 'X' } }] });
    const ai: AiConfig = { provider: 'anthropic', model: 'claude-sonnet-5-5', baseUrl: 'https://api.anthropic.com', apiKey: 'sk-ant', timeoutMs: 1000, fetchImpl };
    expect(await callModel(ai, 'system', 'user')).toEqual({ name: 'X' });
    expect(calls[0].url).toBe('https://api.anthropic.com/v1/messages');
    expect(calls[0].headers).toMatchObject({ 'x-api-key': 'sk-ant', 'anthropic-version': '2023-06-01' });
    expect(calls[0].body).toMatchObject({ model: 'claude-sonnet-5-5', system: 'system', tool_choice: { type: 'tool', name: 'propose_schedule' } });
  });

  it('uses function calling on OpenAI-compatible APIs, and reads JSON text from local models', async () => {
    const tool = capture({ choices: [{ message: { tool_calls: [{ function: { name: 'propose_schedule', arguments: '{"name":"Y"}' } }] } }] });
    const ai: AiConfig = { provider: 'openai', model: 'llama3.1', baseUrl: 'http://ollama:11434/v1', timeoutMs: 1000, fetchImpl: tool.fetchImpl };
    expect(await callModel(ai, 's', 'u')).toEqual({ name: 'Y' });
    expect(tool.calls[0].url).toBe('http://ollama:11434/v1/chat/completions');
    expect(tool.calls[0].headers.authorization).toBeUndefined();
    const text = capture({ choices: [{ message: { content: 'Sure!\n```json\n{"name":"Z"}\n```' } }] });
    expect(await callModel({ ...ai, fetchImpl: text.fetchImpl }, 's', 'u')).toEqual({ name: 'Z' });
  });

  it('turns provider failures into clear messages', async () => {
    const ai: AiConfig = { provider: 'anthropic', model: 'm', baseUrl: 'https://api.anthropic.com', apiKey: 'bad', timeoutMs: 1000, fetchImpl: capture({ error: { message: 'invalid x-api-key' } }, 401).fetchImpl };
    await expect(callModel(ai, 's', 'u')).rejects.toMatchObject({ code: 'ai_auth' });
    await expect(callModel({ ...ai, fetchImpl: capture({}, 429).fetchImpl }, 's', 'u')).rejects.toMatchObject({ code: 'ai_rate_limited' });
    await expect(callModel({ ...ai, fetchImpl: capture({ content: [] }).fetchImpl }, 's', 'u')).rejects.toMatchObject({ code: 'ai_invalid' });
  });
});

describe('Lineup routes', () => {
  const req = (method: string, url: string, body?: unknown): ProxyRequest => ({
    method, url: `/api/tunarr${url}`, headers: { host: 'lineup.local', ...(body === undefined ? {} : { 'content-type': 'application/json' }) }, body: body === undefined ? undefined : JSON.stringify(body),
  });
  const parse = (response: { body: string | Uint8Array }) => JSON.parse(typeof response.body === 'string' ? response.body : new TextDecoder().decode(response.body));

  async function setup(aiReply: unknown) {
    const tunarr = (async (input: string | URL | Request) => {
      const url = String(input).replace('http://tunarr:8000', '');
      if (url === '/api/programs/search') return Response.json({ results: [{ uuid: SHOW, title: 'Sailor Moon', year: 1992, genres: [{ name: 'Anime' }], grandchildCount: 200, type: 'show' }], totalHits: 1 });
      if (url === '/api/smart_collections') return Response.json([{ uuid: COLLECTION, name: 'Ghibli' }]);
      if (url === '/api/filler-lists') return Response.json([{ id: ADS, name: 'Commercials 90s' }]);
      if (url === '/api/channels/chan-1') return Response.json({ id: 'chan-1', name: 'Kids', number: 4 });
      if (url === '/api/channels/chan-1/programming') return Response.json({ lineup: [{ type: 'content', id: 'p1' }, { type: 'content', id: 'p1' }], programs: { p1: { program: { type: 'episode', title: 'E1', show: { title: 'Sailor Moon' } } } } });
      return Response.json([]);
    }) as typeof fetch;
    const prompts: string[] = [];
    const aiFetch = (async (_url: string, init: RequestInit) => {
      prompts.push(String(init.body));
      return Response.json({ content: [{ type: 'tool_use', input: aiReply }] });
    }) as unknown as typeof fetch;
    const config: ProxyConfig = {
      ...createProxyConfig({ TUNARR_URL: 'http://tunarr:8000' }),
      fetchImpl: tunarr,
      templates: createTemplateStore(await mkdtemp(path.join(tmpdir(), 'lineup-routes-'))),
      ai: { provider: 'anthropic', model: 'claude-sonnet-5-5', baseUrl: 'https://api.anthropic.com', apiKey: 'secret-key', timeoutMs: 1000, fetchImpl: aiFetch },
    };
    return { config, prompts };
  }

  it('writes a template from a prompt with the library and channel as context', async () => {
    const { config, prompts } = await setup(proposal);
    expect(parse(await handleTunarrApi(req('GET', '/ai'), config))).toEqual({ enabled: true, provider: 'anthropic', model: 'claude-sonnet-5-5' });
    const response = await handleTunarrApi(req('POST', '/ai/template', { prompt: 'Saturday-morning cartoons', channelId: 'chan-1', includeLibrary: true }), config);
    expect(response.status).toBe(200);
    const body = parse(response);
    expect(body.template.id).toMatch(/^ai-[0-9a-f]{10}$/);
    expect(body.template.defaults.anime.label).toBe('Sailor Moon');
    expect(JSON.stringify(body)).not.toContain('secret-key');
    const sent = JSON.parse(prompts[0]).messages[0].content as string;
    expect(sent).toContain('PROMPT: Saturday-morning cartoons');
    expect(sent).toContain('TARGET CHANNEL: CH 4 "Kids"');
    expect(sent).toContain('- show: Sailor Moon (2)');
    expect(sent).toContain(`${SHOW} | Sailor Moon`);
  });

  it('validates prompts and reports when AI is off', async () => {
    const { config } = await setup(proposal);
    expect((await handleTunarrApi(req('POST', '/ai/template', { prompt: '' }), config)).status).toBe(400);
    expect((await handleTunarrApi(req('POST', '/ai/template', { prompt: 'x', channelId: '../x' }), config)).status).toBe(400);
    const off = { ...config, ai: { off: 'AI is not set up.' } };
    expect(parse(await handleTunarrApi(req('GET', '/ai'), off))).toEqual({ enabled: false, message: 'AI is not set up.' });
    expect((await handleTunarrApi(req('POST', '/ai/template', { prompt: 'x' }), off)).status).toBe(503);
    expect((await handleTunarrApi({ ...req('POST', '/ai/template', { prompt: 'x' }), headers: { host: 'lineup.local', origin: 'https://evil.example', 'content-type': 'application/json' } }, config)).status).toBe(403);
  });

  it('saves, updates and deletes templates', async () => {
    const { config } = await setup(proposal);
    const template = { name: 'Mine', roles: [{ id: 'a', label: 'A', order: 'shuffle' }], days: { all: [['06:00', 'a']] }, ads: { commercialsAt: [], promosAt: [] } };
    const created = parse(await handleTunarrApi(req('POST', '/templates', { ...template, id: 'jp-nhk-g' }), config));
    // The server picks the id, so a saved template can never shadow a built-in one.
    expect(created.id).toMatch(/^my-[0-9a-f]{10}$/);
    expect(created.custom).toBe(true);
    expect((await handleTunarrApi(req('PUT', `/templates/${created.id}`, { ...template, name: 'Renamed' }), config)).status).toBe(200);
    expect(parse(await handleTunarrApi(req('GET', '/templates'), config)).map((item: { name: string }) => item.name)).toEqual(['Renamed']);
    expect((await handleTunarrApi(req('POST', '/templates', { ...template, days: { all: [['99:00', 'a']] } }), config)).status).toBe(400);
    expect((await handleTunarrApi(req('DELETE', `/templates/${created.id}`), config)).status).toBe(200);
    expect((await handleTunarrApi(req('DELETE', `/templates/${created.id}`), config)).status).toBe(404);
    expect((await handleTunarrApi(req('DELETE', '/templates/..%2Fx'), config)).status).toBe(400);
  });
});
