// @vitest-environment jsdom
import { cleanup, fireEvent, render, screen, waitFor, within } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import Home from '../app/page';
import { draftStore } from '../lib/draftStore';
import { dayRange, lineupIndexAt, type LineupItem } from '../lib/lineup';
import { keptStartTime, lineupLength, programmingVersion } from '../server/lineupVersion';
import { guideFor, mixedLineup, mixedPrograms } from './fixtures';

type Reply = { status: number; body: unknown } | 'network-error';

const FILLER_ID = 'f0000000-0000-4000-8000-0000000000f1';
const ID_LIST = 'f0000000-0000-4000-8000-0000000000f2';
const SPOT_ID = 'd0000000-0000-4000-8000-0000000000d1';
const IDENT_A = 'd0000000-0000-4000-8000-0000000000a1';
const IDENT_B = 'd0000000-0000-4000-8000-0000000000a2';
const IDENT_C = 'd0000000-0000-4000-8000-0000000000a3';
const OWN_ID_LIST = 'f0000000-0000-4000-8000-0000000000f3';
const NEWS_ID = 'd0000000-0000-4000-8000-0000000000a4';
const MOVIES_ID = 'd0000000-0000-4000-8000-0000000000a5';
const CUSTOM_ID = 'c0000000-0000-4000-8000-0000000000c1';
const PROFILE_ID = 'p0000000-0000-4000-8000-000000000001';
const PROFILE_720 = 'p0000000-0000-4000-8000-000000000002';
const SMART_ID = '5a000000-0000-4000-8000-0000000000a1';
const AI_PROPOSAL = {
  template: {
    id: 'ai-0123456789', name: 'AI Saturday cartoons', description: 'Cartoons all morning.', inspiredBy: 'Generated by AI from your prompt', region: 'Anywhere', padMs: 1800000, latenessMs: 900000,
    ads: { label: 'Toy commercials', commercialsAt: ['mid', 'post'], promosAt: ['pre'], midRoll: { everyMin: 7, breakMin: 2, maxBreaks: 3, minProgramMin: 15 } },
    roles: [{ id: 'cartoons', label: 'Cartoons', hint: 'Animated series', order: 'shuffle' }],
    days: { all: [['07:00', 'cartoons'], ['12:00', 'cartoons', 'none']] },
    defaults: { cartoons: { key: 'show:show-1', label: 'Bravo Show', template: { type: 'show', showId: 'show-1', show: { title: 'Bravo Show' }, order: 'shuffle', direction: 'asc' } } },
  },
  lists: { commercials: 'f0000000-0000-4000-8000-0000000000f1' },
  notes: 'Your library has no live-action kids shows.',
};
const LIBRARY_MOVIE = { uuid: 'a1b2c3d4-0000-4000-8000-0000000000d1', type: 'movie', title: 'Zulu Movie', year: 1999, duration: 90 * 60_000 };
/** A downloaded series whose titles came in two languages (every third one in English). */
const SERIES = Array.from({ length: 153 }, (_, i) => ({
  uuid: `e0000000-0000-4000-8000-${String(i + 1).padStart(12, '0')}`, type: 'other_video', duration: 50 * 60_000,
  title: (i + 1) % 3 === 2 ? `Chapter ${i + 1} - Widows and Children of Rock & Roll` : `Capítulo ${i + 1} - Viudas e Hijos del Rock & Roll`,
}));

const today = () => {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}`;
};

/** A stateful fake of the companion's /api/tunarr routes. */
function fakeCompanion(options: { schedule?: { type: string; slots: unknown[]; [key: string]: unknown }; health?: Reply; programming?: Reply; lineupStatus?: number; lineup?: LineupItem[]; startTime?: number; stationIds?: boolean; ownStationIds?: boolean; namedIds?: boolean } = {}) {
  const startTime = options.startTime ?? dayRange(today()).from.getTime() - 60 * 60_000;
  const state = {
    lineup: options.lineup ?? (mixedLineup() as LineupItem[]),
    previewedSlots: undefined as unknown,
    fillerLists: [{ id: FILLER_ID, name: 'Station Ads', contentCount: 3, synced: false }, ...(options.stationIds ? [{ id: ID_LIST, name: 'Channel 3 idents', contentCount: 2, synced: false }] : []), ...(options.ownStationIds ? [{ id: OWN_ID_LIST, name: 'Newsroom idents', contentCount: 1, synced: false }] : [])] as Array<{ id: string; name: string; contentCount?: number; synced: boolean }>,
    fillerRoles: { ...(options.stationIds ? { [ID_LIST]: 'station-id' } : {}), ...(options.ownStationIds ? { [OWN_ID_LIST]: 'station-id' } : {}) } as Record<string, string>,
    listPrograms: {
      [FILLER_ID]: [{ type: 'content', id: SPOT_ID, duration: 30_000, program: { type: 'other_video', title: 'Cola Spot' } }],
      [ID_LIST]: [
        { type: 'content', id: IDENT_A, duration: 10_000, program: { type: 'other_video', title: 'Ident Sunrise' } },
        { type: 'content', id: IDENT_B, duration: 10_000, program: { type: 'other_video', title: 'Ident Night' } },
        // Named for a channel, like "EL 7 ID.mp4" in the upload folder.
        ...(options.namedIds ? [
          { type: 'content', id: MOVIES_ID, duration: 8_000, program: { type: 'other_video', title: 'MOVIE NIGHT ID' } },
          { type: 'content', id: NEWS_ID, duration: 12_000, program: { type: 'other_video', title: 'NEWSROOM ID v2' } },
        ] : []),
      ],
      [OWN_ID_LIST]: [{ type: 'content', id: IDENT_C, duration: 5_000, program: { type: 'other_video', title: 'Newsroom ident' } }],
    } as Record<string, unknown[]>,
    templates: [] as unknown[],
    sources: [{ id: 'src-1', name: 'Plex', type: 'plex', libraries: [{ id: 'lib-movies', name: 'Movies', mediaType: 'movies', enabled: true }] }] as Array<{ id: string; name: string; type: string; libraries: unknown[] }>,
    settings: { id: 'chan-news', name: 'Newsroom', number: 3, streamMode: 'hls', transcodeConfigId: 'p0000000-0000-4000-8000-000000000001', icon: { path: '' }, fillerCollections: (options.ownStationIds ? [{ id: OWN_ID_LIST, weight: 1, cooldownSeconds: 0 }] : []) as unknown[], fillerRepeatCooldown: 30000, disableFillerOverlay: false, guideMinimumDuration: 30000, guideFlexTitle: '', groupTitle: 'tunarr', startTime },
  };
  const channels: Array<{ id: string; name: string; number: number; startTime: number; duration: number; programCount: number; icon?: { path: string } }> = [
    { id: 'chan-movies', name: 'Movie Night', number: 7, startTime, duration: 140 * 60_000, programCount: 6, icon: { path: 'http://host.docker.internal:8000/images/uploads/movies.png' } },
    { id: 'chan-news', name: 'Newsroom', number: 3, startTime, duration: 140 * 60_000, programCount: 6 },
  ];
  const requests: Array<{ method: string; path: string; search: URLSearchParams; body?: unknown }> = [];
  const reply = (r: Reply) => (r === 'network-error' ? Promise.reject(new TypeError('Failed to fetch')) : Promise.resolve(new Response(JSON.stringify(r.body), { status: r.status })));

  const fetchMock = vi.fn((input: string | URL | Request, init?: RequestInit) => {
    const url = new URL(String(input), 'http://lineup.local');
    const method = init?.method ?? 'GET';
    requests.push({ method, path: url.pathname, search: url.searchParams, body: init?.body ? JSON.parse(String(init.body)) : undefined });
    if (!url.pathname.startsWith('/api/tunarr/')) throw new Error(`Unexpected request to ${url}`);
    if (url.pathname === '/api/tunarr/health') return reply(options.health ?? { status: 200, body: { status: 'connected', tunarrHost: 'tunarr:8000', channelCount: 2 } });
    if (url.pathname === '/api/tunarr/channels') return reply({ status: 200, body: channels });
    // Library and lists (see server/content.ts for the real routes).
    if (url.pathname === '/api/tunarr/media-sources') return reply({ status: 200, body: [{ id: 'src-1', name: 'Plex', type: 'plex', libraries: [{ id: 'lib-movies', name: 'Movies', mediaType: 'movies' }, { id: 'lib-videos', name: 'Viudas', mediaType: 'other_videos' }] }] });
    if (url.pathname === '/api/tunarr/library/search') {
      const query = JSON.parse(String(init!.body)) as { type?: string; libraryId?: string; page?: number; limit?: number };
      if (query.libraryId === 'lib-videos') {
        // Like Tunarr: plain alphabetical order, a page at a time.
        const all = SERIES.slice().sort((a, b) => (a.title < b.title ? -1 : 1));
        const limit = query.limit ?? 40;
        const at = query.page ?? 0;
        return reply({ status: 200, body: { results: all.slice(at * limit, (at + 1) * limit), page: at, totalPages: Math.ceil(all.length / limit), totalHits: all.length } });
      }
      if (query.type === 'season') return reply({ status: 200, body: { results: [1, 2, 3].map((index) => ({ uuid: `season-${index}`, type: 'season', title: `Season ${index}`, index, childCount: 10 })), page: 0, totalPages: 1, totalHits: 3 } });
      return reply({ status: 200, body: { results: [LIBRARY_MOVIE], page: 0, totalPages: 1, totalHits: 1 } });
    }
    // Tunarr setup (see server/admin.ts for the real routes).
    if (url.pathname === '/api/tunarr/channels/create') {
      const body = JSON.parse(String(init!.body)) as { name: string; number: number };
      channels.push({ id: 'chan-new', name: body.name, number: body.number, startTime, duration: 0, programCount: 0 });
      return reply({ status: 201, body: { id: 'chan-new', name: body.name, number: body.number } });
    }
    if (method === 'DELETE' && /^\/api\/tunarr\/channels\/[^/]+$/.test(url.pathname)) {
      channels.splice(channels.findIndex((channel) => url.pathname.endsWith(`/${channel.id}`)), 1);
      return reply({ status: 200, body: { deleted: true } });
    }
    if (url.pathname === '/api/tunarr/transcode-configs') return reply({ status: 200, body: [{ id: PROFILE_ID, name: 'Default', isDefault: true, resolution: { widthPx: 1920, heightPx: 1080 }, videoFormat: 'h264' }, { id: PROFILE_720, name: 'Light', isDefault: false, resolution: { widthPx: 1280, heightPx: 720 }, videoFormat: 'h264' }] });
    if (url.pathname === '/api/tunarr/media-sources/manage') return reply({ status: 200, body: state.sources });
    if (url.pathname === '/api/tunarr/media-sources/add') {
      state.sources.push({ id: 'src-2', name: (JSON.parse(String(init!.body)) as { name: string }).name, type: 'plex', libraries: [] });
      return reply({ status: 201, body: { id: 'src-2' } });
    }
    // Saved templates and the AI assistant (see server/lineupRoutes.ts).
    if (url.pathname === '/api/tunarr/templates' && method === 'GET') return reply({ status: 200, body: state.templates });
    if (url.pathname === '/api/tunarr/templates' && method === 'POST') {
      const saved = { ...(JSON.parse(String(init!.body)) as object), id: `my-${state.templates.length + 1}`, custom: true };
      state.templates.push(saved as never);
      return reply({ status: 201, body: saved });
    }
    if (url.pathname.startsWith('/api/tunarr/templates/') && method === 'PUT') {
      const saved = { ...(JSON.parse(String(init!.body)) as object), id: url.pathname.split('/').pop(), custom: true };
      state.templates = state.templates.map((item) => ((item as { id: string }).id === saved.id ? saved : item)) as never;
      return reply({ status: 200, body: saved });
    }
    if (url.pathname === '/api/tunarr/ai') return reply({ status: 200, body: { enabled: true, provider: 'anthropic', model: 'claude-sonnet-5-5' } });
    if (url.pathname === '/api/tunarr/ai/template') return reply({ status: 200, body: AI_PROPOSAL });
    if (url.pathname === '/api/tunarr/smart-collections/preview') return reply({ status: 200, body: { totalHits: 12, sample: [{ id: 'm1', title: 'Toy Story', type: 'movie', year: 1995 }] } });
    if (url.pathname === '/api/tunarr/smart-collections/create') {
      const body = JSON.parse(String(init!.body)) as { name: string };
      return reply({ status: 201, body: { id: SMART_ID, name: body.name, keywords: '', rules: { match: 'all', rules: [] }, description: '', filterString: '' } });
    }
    if (url.pathname === '/api/tunarr/custom-shows') return reply({ status: 200, body: [{ id: CUSTOM_ID, name: 'Marathon', contentCount: 2, synced: false }] });
    if (url.pathname === '/api/tunarr/smart-collections') return reply({ status: 200, body: [] });
    if (url.pathname === '/api/tunarr/filler-lists' && method === 'GET') return reply({ status: 200, body: state.fillerLists });
    const listPrograms = /^\/api\/tunarr\/filler-lists\/([^/]+)\/programs$/.exec(url.pathname);
    if (listPrograms) return reply({ status: 200, body: state.listPrograms[listPrograms[1]] ?? [] });
    if (url.pathname === '/api/tunarr/filler-roles') return reply({ status: 200, body: state.fillerRoles });
    // The desk picks up filler folders on load; this companion has none.
    if (url.pathname === '/api/tunarr/filler-folders/sync') return reply({ status: 200, body: { connected: false, created: [], updated: [], errors: [] } });
    const role = /^\/api\/tunarr\/filler-roles\/([^/]+)$/.exec(url.pathname);
    if (role) {
      if (method === 'DELETE') delete state.fillerRoles[role[1]];
      else state.fillerRoles[role[1]] = (JSON.parse(String(init!.body)) as { role: string }).role;
      return reply({ status: 200, body: { ...state.fillerRoles } });
    }
    if (url.pathname === '/api/tunarr/filler-lists' && method === 'POST') {
      const created = JSON.parse(String(init!.body)) as { name: string; programs: unknown[] };
      state.fillerLists.push({ id: 'f0000000-0000-4000-8000-0000000000f9', name: created.name, contentCount: created.programs.length, synced: false });
      return reply({ status: 201, body: { id: 'f0000000-0000-4000-8000-0000000000f9' } });
    }
    if (url.pathname === '/api/tunarr/channels/chan-news/settings') {
      if (method === 'PUT') Object.assign(state.settings, JSON.parse(String(init!.body)));
      return reply({ status: 200, body: state.settings });
    }
    const match = /^\/api\/tunarr\/channels\/([^/]+)\/(programming|lineup|schedule|schedule-preview)$/.exec(url.pathname);
    if (match?.[2] === 'schedule') return reply({ status: 200, body: { schedule: options.schedule } });
    if (match?.[2] === 'schedule-preview') {
      const { slots } = JSON.parse(String(init!.body)) as { slots: unknown[] };
      state.previewedSlots = slots;
      return reply({ status: 200, body: { startTime, lineup: [...state.lineup].reverse(), programs: mixedPrograms(), seed: [11, 22], discardCount: 3 } });
    }
    if (match?.[2] === 'programming' && method === 'POST') {
      // Like the companion: refuse saves based on an outdated version.
      const ifMatch = String((init?.headers as Record<string, string>)['if-match'] ?? '').replaceAll('"', '');
      if (ifMatch !== programmingVersion(state.lineup, options.schedule)) {
        return reply({ status: 412, body: { error: { code: 'lineup_changed', message: 'This channel changed in Tunarr since it was loaded. Nothing was saved.' } } });
      }
      const saved = JSON.parse(String(init!.body)) as { type: string; lineup?: LineupItem[]; keepOnAir?: boolean };
      let moved: number | undefined;
      if (saved.keepOnAir) {
        // Like the companion: move the channel's start so the pass on air stays put.
        const channel = channels.find((item) => item.id === match[1])!;
        moved = keptStartTime(channel.startTime, lineupLength(state.lineup), lineupLength(saved.lineup), Date.now());
        channel.startTime = moved;
      }
      if (saved.type === 'manual') state.lineup = saved.lineup!;
      else state.lineup = [...state.lineup].reverse();
      return reply({ status: 200, body: { lineup: state.lineup, programs: mixedPrograms(), ...(moved !== undefined ? { startTime: moved } : {}) } });
    }
    if (match?.[2] === 'programming') {
      return reply(options.programming ?? { status: 200, body: { lineup: state.lineup, programs: mixedPrograms(), totalPrograms: 6, schedule: options.schedule } });
    }
    if (match?.[2] === 'lineup') {
      if (options.lineupStatus) return reply({ status: options.lineupStatus, body: { error: { code: 'tunarr_error', message: 'Guide failed' } } });
      const from = new Date(url.searchParams.get('from')!).getTime();
      const to = new Date(url.searchParams.get('to')!).getTime();
      return reply({ status: 200, body: { id: match[1], programs: guideFor(state.lineup, channels.find((item) => item.id === match[1])?.startTime ?? startTime, from, to) } });
    }
    return reply({ status: 404, body: { error: { code: 'route_not_allowed', message: 'nope' } } });
  });
  vi.stubGlobal('fetch', fetchMock);
  return { requests, state, fetchMock };
}

const count = (requests: ReturnType<typeof fakeCompanion>['requests'], method: string, path: string) => requests.filter((r) => r.method === method && r.path === path).length;

/**
 * A channel opens with what's on air selected, which depends on the clock.
 * Tests that act on "the selection" pick the day's first Alpha Movie row
 * (lineup item 0) first, as a user would.
 */
const pickAlpha = async () => {
  await screen.findAllByText('Alpha Movie');
  fireEvent.click([...document.querySelectorAll<HTMLElement>('.program')].find((row) => row.textContent?.includes('Alpha Movie'))!);
};

beforeEach(async () => {
  vi.unstubAllGlobals();
  // Drafts outlive a render on purpose; tests must not see each other's.
  const store = draftStore();
  for (const draft of await store.list()) await store.delete(draft.channelId);
});
afterEach(() => {
  cleanup();
  vi.unstubAllGlobals();
});

describe('live mode', () => {
  it('loads real channels, the first channel’s programming and Tunarr’s guide for today', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    expect(await screen.findByText('Movie Night')).toBeTruthy();
    expect(screen.getByText('Newsroom')).toBeTruthy();
    expect(screen.getByText('Tunarr connected')).toBeTruthy();
    // Channels are sorted by number, so Newsroom (3) loads first.
    await waitFor(() => expect(requests.some((r) => r.path === '/api/tunarr/channels/chan-news/programming')).toBe(true));
    await screen.findAllByText('Alpha Movie');
    const lineupCall = await waitFor(() => {
      const call = requests.find((r) => r.path === '/api/tunarr/channels/chan-news/lineup');
      expect(call).toBeTruthy();
      return call!;
    });
    const { from, to } = dayRange(today());
    expect(lineupCall.search.get('from')).toBe(from.toISOString());
    expect(lineupCall.search.get('to')).toBe(to.toISOString());
    // Every request stays on this app's origin.
    expect(requests.every((r) => r.path.startsWith('/api/tunarr/'))).toBe(true);
    expect(screen.queryByText('Studio Selects')).toBeNull();
  });

  it('requests the matching date range when navigating days', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('button', { name: 'Next day' }));
    const next = new Date(`${today()}T12:00:00`);
    next.setDate(next.getDate() + 1);
    const { from, to } = dayRange(`${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, '0')}-${String(next.getDate()).padStart(2, '0')}`);
    await waitFor(() => expect(requests.some((r) => r.path.endsWith('/lineup') && r.search.get('from') === from.toISOString() && r.search.get('to') === to.toISOString())).toBe(true));
  });

  it('saves a reordered lineup, preserving every item, then re-fetches programming and the guide', async () => {
    const { requests, state } = fakeCompanion();
    const original = mixedLineup();
    render(<Home />);
    await pickAlpha();
    await waitFor(() => expect(count(requests, 'GET', '/api/tunarr/channels/chan-news/lineup')).toBe(1));

    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    expect(await screen.findByText(/Showing unsaved changes/)).toBeTruthy();
    expect(screen.getAllByRole('button', { name: 'Undo' }).length).toBeGreaterThan(0);
    expect(screen.getByText('Moved “Alpha Movie” later')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));

    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    const post = requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!;
    expect(post.body).toEqual({ type: 'manual', lineup: JSON.parse(JSON.stringify([original[1], original[0], ...original.slice(2)])), append: false });
    expect(state.lineup[0].type).toBe('flex');

    // Initial load and the re-read after saving (the version check happens in the companion).
    await waitFor(() => expect(count(requests, 'GET', '/api/tunarr/channels/chan-news/programming')).toBe(2));
    await waitFor(() => expect(count(requests, 'GET', '/api/tunarr/channels/chan-news/lineup')).toBe(2));
    expect(await screen.findByRole('button', { name: 'Saved' })).toBeTruthy();
    expect(screen.queryByText(/Showing unsaved changes/)).toBeNull();
    expect(screen.getByRole('status').textContent).toBe('Lineup saved to Tunarr');
  });

  it('undoes and redoes step by step, and reverts everything', async () => {
    fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    expect(screen.getByText('EDIT LIST (2)')).toBeTruthy();
    fireEvent.click(screen.getAllByRole('button', { name: 'Undo' })[0]);
    expect(screen.getByText('EDIT LIST (1)')).toBeTruthy();
    expect(screen.getByRole('button', { name: 'Save lineup' })).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Redo' }));
    expect(screen.getByText('EDIT LIST (2)')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Revert all' }));
    expect(await screen.findByRole('button', { name: 'Saved' })).toBeTruthy();
  });

  it('warns before saving over a generated schedule', async () => {
    const { requests } = fakeCompanion({ schedule: { type: 'time', slots: [] } });
    render(<Home />);
    await pickAlpha();
    expect(screen.getByText('Generated schedule')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));

    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    const dialog = await screen.findByRole('alertdialog');
    expect(within(dialog).getByText('Save over a generated schedule?')).toBeTruthy();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Cancel' }));
    expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(0);
    expect(screen.getByRole('button', { name: 'Save lineup' })).toBeTruthy();

    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    fireEvent.click(within(await screen.findByRole('alertdialog')).getByRole('button', { name: 'Save manual lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
  });

  it('keeps changes and reports the error when a save fails', async () => {
    const { fetchMock } = fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    const passthrough = fetchMock.getMockImplementation()!;
    fetchMock.mockImplementation((input, init) => (init?.method === 'POST'
      ? Promise.resolve(new Response(JSON.stringify({ error: { code: 'tunarr_rejected', message: 'Number must be greater than 0' } }), { status: 400 }))
      : passthrough(input, init)));
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    expect(await screen.findByText('Not saved: Number must be greater than 0')).toBeTruthy();
    expect(screen.getByRole('button', { name: 'Save lineup' })).toBeTruthy();
  });

  it('keeps unsaved changes and the edit list per channel when switching channels', async () => {
    fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    fireEvent.click(screen.getByText('Movie Night'));
    await waitFor(() => expect(document.querySelector('.channel.active')?.textContent).toContain('Movie Night'));
    expect(screen.queryByRole('alertdialog')).toBeNull();
    expect(await screen.findByText('· unsaved')).toBeTruthy();
    await screen.findByRole('button', { name: 'Saved' });
    fireEvent.click(screen.getByText('Newsroom'));
    expect(await screen.findByRole('button', { name: 'Save lineup' })).toBeTruthy();
    expect(screen.getByText('Moved “Alpha Movie” later')).toBeTruthy();
  });

  it('restores unsaved changes and undo history after a reload', async () => {
    fakeCompanion();
    const first = render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    await waitFor(async () => expect((await draftStore().get('chan-news'))?.past).toHaveLength(2));
    first.unmount();
    render(<Home />);
    expect(await screen.findByText(/Restored your unsaved changes \(2 edits\)/)).toBeTruthy();
    expect(screen.getByText('EDIT LIST (2)')).toBeTruthy();
    fireEvent.click(screen.getAllByRole('button', { name: 'Undo' })[0]);
    expect(screen.getByText('EDIT LIST (1)')).toBeTruthy();
  });

  it('keeps the edit list after saving, so a save can be undone', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    expect(await screen.findByRole('button', { name: 'Saved' })).toBeTruthy();
    expect(screen.getByText('Moved “Alpha Movie” later')).toBeTruthy();
    fireEvent.click(screen.getAllByRole('button', { name: 'Undo' })[0]);
    fireEvent.click(await screen.findByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(2));
    const posts = requests.filter((r) => r.method === 'POST' && r.path.endsWith('/programming'));
    expect((posts[1].body as { lineup: LineupItem[] }).lineup.map((item) => item.id ?? item.type)).toEqual(mixedLineup().map((item) => item.id ?? item.type));
  });

  it('drops a stored draft when Tunarr’s lineup changed since it was made', async () => {
    const { state } = fakeCompanion();
    const first = render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    await waitFor(async () => expect((await draftStore().get('chan-news'))?.dirty).toBe(true));
    first.unmount();
    state.lineup = [...state.lineup].reverse();
    render(<Home />);
    expect(await screen.findByText(/changed in Tunarr since you last edited it here/)).toBeTruthy();
    expect(screen.getByRole('button', { name: 'Saved' })).toBeTruthy();
  });
});

describe('no silent fallback to demo mode', () => {
  it('shows the unreachable host and waits for an explicit demo choice', async () => {
    fakeCompanion({ health: { status: 502, body: { status: 'unreachable', tunarrHost: '192.168.1.50:8000', error: { code: 'tunarr_unreachable', message: 'Could not reach Tunarr at 192.168.1.50:8000 (ECONNREFUSED).' } } } });
    render(<Home />);
    const dialog = await screen.findByRole('dialog');
    expect(within(dialog).getByText('Can’t reach Tunarr')).toBeTruthy();
    expect(within(dialog).getByText('Could not reach Tunarr at 192.168.1.50:8000 (ECONNREFUSED).')).toBeTruthy();
    expect(within(dialog).getByText('192.168.1.50:8000')).toBeTruthy();
    expect(screen.getByText('Tunarr unreachable')).toBeTruthy();
    expect(screen.queryByText('Studio Selects')).toBeNull();
    expect(screen.queryByText('Demo mode')).toBeNull();

    fireEvent.click(within(dialog).getByRole('button', { name: 'Use demo data' }));
    expect(await screen.findByText('Studio Selects')).toBeTruthy();
    expect(screen.getByText('Demo mode')).toBeTruthy();
    expect(screen.getByText('DEMO CHANNELS')).toBeTruthy();
  });

  it('explains how to configure TUNARR_URL when it is missing', async () => {
    fakeCompanion({ health: { status: 503, body: { status: 'not_configured', error: { code: 'not_configured', message: 'TUNARR_URL is not set on the Lineup server.' } } } });
    render(<Home />);
    const dialog = await screen.findByRole('dialog');
    expect(within(dialog).getByText('Tunarr isn’t configured')).toBeTruthy();
    expect(within(dialog).getByText('TUNARR_URL=http://tunarr:8000')).toBeTruthy();
    expect(screen.queryByText('Studio Selects')).toBeNull();
  });

  it('treats a missing companion (hosted preview) as unavailable, not demo', async () => {
    vi.stubGlobal('fetch', vi.fn(() => Promise.resolve(new Response('<!doctype html><p>Not found</p>', { status: 404 }))));
    render(<Home />);
    const dialog = await screen.findByRole('dialog');
    expect(within(dialog).getByText('Live mode unavailable')).toBeTruthy();
    expect(screen.queryByText('Studio Selects')).toBeNull();
  });

  it('stays live with an error when programming fails to load', async () => {
    fakeCompanion({ programming: { status: 504, body: { error: { code: 'tunarr_timeout', message: 'Tunarr at tunarr:8000 did not respond within 10 seconds.', tunarrHost: 'tunarr:8000' } } } });
    render(<Home />);
    expect(await screen.findByText('Couldn’t load this channel')).toBeTruthy();
    expect(screen.getByText('Tunarr at tunarr:8000 did not respond within 10 seconds.')).toBeTruthy();
    expect(screen.getByText('Tunarr unreachable')).toBeTruthy();
    expect(screen.getByText('Movie Night')).toBeTruthy();
    expect(screen.queryByText('Studio Selects')).toBeNull();
    expect(screen.queryByText('Demo mode')).toBeNull();
  });

  it('falls back to a lineup projection, labeled, when the guide fails', async () => {
    fakeCompanion({ lineupStatus: 502 });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    expect(await screen.findByText(/guide for this date did not load \(Guide failed\)/)).toBeTruthy();
    expect(screen.queryByText('Demo mode')).toBeNull();
  });
});

const lineupOrder = (requests: ReturnType<typeof fakeCompanion>['requests']) =>
  (requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!.body as { lineup: LineupItem[] }).lineup.map((item) => item.id ?? item.type);

describe('programming desk tools', () => {
  it('refuses to overwrite changes made elsewhere since loading', async () => {
    const { requests, state } = fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    // Someone edits the channel in Tunarr's own UI meanwhile.
    state.lineup = [...state.lineup].reverse();
    const elsewhere = state.lineup;
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    const dialog = await screen.findByRole('alertdialog');
    expect(within(dialog).getByText('This channel changed in Tunarr')).toBeTruthy();
    // The companion refused the write, so the edit made elsewhere survives.
    expect(state.lineup).toBe(elsewhere);
    fireEvent.click(within(dialog).getByRole('button', { name: 'Keep my edits' }));
    expect(screen.getByRole('button', { name: 'Save lineup' })).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    fireEvent.click(within(await screen.findByRole('alertdialog')).getByRole('button', { name: 'Reload from Tunarr' }));
    expect(await screen.findByRole('button', { name: 'Saved' })).toBeTruthy();
    expect(state.lineup).toBe(elsewhere);
    expect(count(requests, 'GET', '/api/tunarr/channels/chan-news/programming')).toBe(2);
  });

  it('picks up, slides and drops with the remote (arrow keys + OK)', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    // Select the first Alpha Movie row, then OK to pick up.
    fireEvent.click(screen.getAllByRole('button', { name: /Alpha Movie/ }).find((element) => element.classList.contains('program'))!);
    const row = document.querySelector<HTMLButtonElement>('.program.cursor')!;
    fireEvent.keyDown(row, { key: 'Enter' });
    expect(screen.getByText('moving')).toBeTruthy();
    fireEvent.keyDown(row, { key: 'ArrowDown' });
    fireEvent.keyDown(row, { key: 'ArrowDown' });
    fireEvent.keyDown(document.querySelector('.program.cursor')!, { key: 'Enter' });
    expect(screen.queryByText('moving')).toBeNull();
    expect(screen.getByText('Moved “Alpha Movie” 2 places later')).toBeTruthy();
    fireEvent.keyDown(document.body, { key: 's', metaKey: true });
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(lineupOrder(requests)).toEqual(['flex', 'prog-custom', 'prog-alpha', '8f3c1b2a-0000-4000-8000-000000000002', 'redirect', 'prog-bravo']);
  });

  it('cancels a slide with Back and leaves the lineup untouched', async () => {
    fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getAllByRole('button', { name: /Alpha Movie/ }).find((element) => element.classList.contains('program'))!);
    fireEvent.keyDown(document.querySelector('.program.cursor')!, { key: 'Enter' });
    fireEvent.keyDown(document.querySelector('.program.cursor')!, { key: 'ArrowDown' });
    fireEvent.keyDown(document.querySelector('.program.cursor')!, { key: 'Escape' });
    expect(await screen.findByRole('button', { name: 'Saved' })).toBeTruthy();
  });

  it('moves a shift-selected block together', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    const rows = () => [...document.querySelectorAll<HTMLButtonElement>('.program')];
    const alpha = rows().find((element) => element.textContent?.includes('Alpha Movie'))!;
    fireEvent.click(alpha);
    const next = rows()[rows().indexOf(alpha) + 1];
    fireEvent.click(next, { shiftKey: true });
    expect(screen.getByText('2 programs selected')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: /Later/ }));
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(lineupOrder(requests)).toEqual(['prog-custom', 'prog-alpha', 'flex', '8f3c1b2a-0000-4000-8000-000000000002', 'redirect', 'prog-bravo']);
  });

  it('moves to a lineup position from the Move dialog', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: 'Move or swap…' }));
    const dialog = await screen.findByRole('dialog');
    fireEvent.change(within(dialog).getByLabelText('Lineup position'), { target: { value: '6' } });
    fireEvent.click(within(within(dialog).getByLabelText('Lineup position').closest('form')!).getByRole('button', { name: 'Move' }));
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(lineupOrder(requests).at(-1)).toBe('prog-alpha');
  });

  it('previews and applies a move to a start time', async () => {
    fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: 'Move or swap…' }));
    const dialog = await screen.findByRole('dialog');
    // The fake channel starts at 23:00 the previous day; its cycle is 140 minutes.
    fireEvent.change(within(dialog).getByLabelText('Start near time'), { target: { value: '00:55:00' } });
    expect(within(dialog).getByText(/^Will start 00:/)).toBeTruthy();
    fireEvent.click(within(within(dialog).getByLabelText('Start near time').closest('form')!).getByRole('button', { name: 'Move' }));
    expect(await screen.findByText(/^Moved “Alpha Movie” to start 00:/)).toBeTruthy();
  });

  it('runs commands from the pull-down menus', async () => {
    fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('menuitem', { name: 'Edit' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Move Later/ }));
    expect(screen.getByText('Moved “Alpha Movie” later')).toBeTruthy();
    fireEvent.click(screen.getByRole('menuitem', { name: 'Help' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Keyboard & Remote Shortcuts/ }));
    expect(await screen.findByText('Keyboard & remote shortcuts')).toBeTruthy();
    fireEvent.keyDown(document.body, { key: 'Escape' });
    expect(screen.queryByText('Keyboard & remote shortcuts')).toBeNull();
  });

  it('lists every menu in one sheet for phones, operable by keyboard', async () => {
    fakeCompanion();
    render(<Home />);
    await pickAlpha();
    const button = screen.getByRole('menuitem', { name: 'Menu' });
    fireEvent.click(button);
    const sheet = screen.getByRole('menu', { name: 'All menus' });
    for (const title of ['File', 'Edit', 'View', 'Channel', 'Lists', 'Setup', 'Help']) expect(within(sheet).getByRole('group', { name: title })).toBeTruthy();
    // Left and right don't wander off to the desktop titles, which phones hide.
    fireEvent.keyDown(sheet, { key: 'ArrowRight' });
    expect(screen.getByRole('menu', { name: 'All menus' })).toBeTruthy();
    fireEvent.keyDown(sheet, { key: 'Escape' });
    expect(screen.queryByRole('menu', { name: 'All menus' })).toBeNull();
    expect(document.activeElement).toBe(button);
    fireEvent.keyDown(button, { key: 'ArrowDown' });
    fireEvent.click(within(screen.getByRole('menu', { name: 'All menus' })).getByRole('menuitem', { name: /Move Later/ }));
    expect(screen.getByText('Moved “Alpha Movie” later')).toBeTruthy();
    expect(screen.queryByRole('menu', { name: 'All menus' })).toBeNull();
  });

  it('expands and collapses Program Info, which narrow screens show as a sheet', async () => {
    fakeCompanion();
    render(<Home />);
    await pickAlpha();
    const toggle = screen.getByRole('button', { name: 'Show details' });
    expect(toggle.getAttribute('aria-expanded')).toBe('false');
    fireEvent.click(toggle);
    expect(screen.getByRole('button', { name: 'Hide details' }).getAttribute('aria-expanded')).toBe('true');
    expect(document.querySelector('.inspector')!.classList.contains('expanded')).toBe(true);
  });

  it('opens each channel with what is on air selected, so Insert goes next to it', async () => {
    fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    const onAirIsSelected = () => {
      const row = document.querySelector('.program.on-air');
      return !!row && row.classList.contains('selected') && row.classList.contains('cursor');
    };
    await waitFor(() => expect(onAirIsSelected()).toBe(true));
    fireEvent.click(screen.getByText('Movie Night'));
    await waitFor(() => expect(document.querySelector('.channel.active')?.textContent).toContain('Movie Night'));
    await waitFor(() => expect(onAirIsSelected()).toBe(true));
    fireEvent.keyDown(document.body, { key: 'i' });
    const insert = await screen.findByRole('dialog', { name: 'Insert into the lineup' });
    // "After" the on-air program: it starts when that one ends (where the next row starts), not on some other day.
    const rows = [...document.querySelectorAll('.program')];
    const next = rows[rows.indexOf(document.querySelector('.program.on-air')!) + 1];
    const placement = within(insert).getByRole('status', { name: 'Insert placement' }).textContent;
    // (Just before midnight the on-air row can be the day's last.)
    if (next) expect(placement).toContain(`${next.querySelector('time')!.textContent!.slice(0, 5)}:`);
    else expect(placement).toMatch(/^Starts /);
  });

  it('marks what is on air and shows day totals', async () => {
    fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    expect(screen.getByText('ON AIR')).toBeTruthy();
    expect(document.querySelector('.program.on-air .now-line')).toBeTruthy();
    const totals = screen.getByRole('group', { name: 'Airtime this day' });
    expect(within(totals).getByText('Programs')).toBeTruthy();
    // The fixture's flex plays from filler lists: a commercial break, not plain flex.
    expect(within(totals).getByText('Commercial breaks')).toBeTruthy();
    expect(within(totals).getByText('Redirects')).toBeTruthy();
  });

  it('exports the day as a program log', async () => {
    fakeCompanion();
    let exported: Blob | undefined;
    Object.defineProperty(URL, 'createObjectURL', { configurable: true, value: (blob: Blob) => { exported = blob; return 'blob:log'; } });
    Object.defineProperty(URL, 'revokeObjectURL', { configurable: true, value: () => {} });
    const click = vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {});
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'File' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Export Program Log/ }));
    expect(click).toHaveBeenCalledOnce();
    const csv = await new Promise<string>((resolve) => {
      const reader = new FileReader();
      reader.onload = () => resolve(String(reader.result));
      reader.readAsText(exported!);
    });
    click.mockRestore();
    expect(csv.split('\r\n')[0]).toBe('Date,Start,End,Duration,Type,Title,Detail,Lineup position');
    expect(csv).toContain('Alpha Movie');
    expect(csv).toContain('Channel Two');
  });

  it('asks before leaving demo edits to connect', async () => {
    fakeCompanion({ health: { status: 502, body: { status: 'unreachable', tunarrHost: 'tunarr:8000', error: { code: 'tunarr_unreachable', message: 'down' } } } });
    render(<Home />);
    fireEvent.click(within(await screen.findByRole('dialog')).getByRole('button', { name: 'Use demo data' }));
    await screen.findByText('Studio Selects');
    // Any edit will do; what's on air may be the lineup's last item.
    fireEvent.click([screen.getByRole('button', { name: /Later/ }), screen.getByRole('button', { name: /Earlier/ })].find((button) => !(button as HTMLButtonElement).disabled)!);
    fireEvent.click(screen.getByRole('button', { name: 'Demo mode' }));
    fireEvent.click(within(await screen.findByRole('dialog')).getByRole('button', { name: 'Connect to Tunarr' }));
    expect(within(await screen.findByRole('alertdialog')).getByText('Discard unsaved changes?')).toBeTruthy();
  });
});

describe('slot schedule editing', () => {
  const schedule = {
    type: 'random',
    maxDays: 2,
    randomDistribution: 'weighted',
    flexPreference: 'end',
    padMs: 0,
    slots: [
      { id: 's1', type: 'show', showId: 'show-1', show: { title: 'Bravo Show' }, order: 'next', direction: 'asc', weight: 3, cooldownMs: 0, durationSpec: { type: 'dynamic', programCount: 1 } },
      { id: 's2', type: 'movie', order: 'shuffle', direction: 'asc', weight: 1, cooldownMs: 600000 },
    ],
  };

  it('edits slots, previews the regenerated lineup, then saves exactly that preview', async () => {
    const { requests, state } = fakeCompanion({ schedule });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('button', { name: 'Edit slot schedule…' }));
    const dialog = await screen.findByRole('dialog', { name: /Slot schedule ·/ });
    expect(within(dialog).getByText(/Random slots \(weighted\) · 2 slots · generates 2 days/)).toBeTruthy();
    expect(within(dialog).getByText('75.0%')).toBeTruthy();
    fireEvent.change(within(dialog).getByLabelText('Slot 2 weight'), { target: { value: '3' } });
    expect(within(dialog).getAllByText('50.0%')).toHaveLength(2);
    // Saving needs a preview of exactly this draft first.
    expect((within(dialog).getByRole('button', { name: 'Save schedule' }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.click(within(dialog).getByRole('button', { name: 'Preview lineup' }));

    expect(await screen.findByRole('region', { name: 'Schedule preview' })).toBeTruthy();
    expect((state.previewedSlots as Array<{ weight: number }>)[1].weight).toBe(3);
    fireEvent.click(within(screen.getByRole('region', { name: 'Schedule preview' })).getByRole('button', { name: 'Save schedule' }));

    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    const post = requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!;
    expect(post.body).toMatchObject({ type: 'random', seed: [11, 22], discardCount: 3 });
    expect((post.body as { schedule: { slots: Array<{ weight: number }> } }).schedule.slots.map((slot) => slot.weight)).toEqual([3, 3]);
    // The fake companion saves the reversed lineup, which is also what it previewed.
    expect(await screen.findByText(/Schedule saved exactly as previewed/)).toBeTruthy();
    expect(screen.queryByRole('region', { name: 'Schedule preview' })).toBeNull();
  });

  it('offers existing sources, every catalog source, and library shows', async () => {
    fakeCompanion({ schedule });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('button', { name: 'Edit slot schedule…' }));
    const dialog = await screen.findByRole('dialog', { name: /Slot schedule ·/ });
    await waitFor(() => expect([...(within(dialog).getByLabelText('Slot 1 source') as unknown as HTMLSelectElement).options].map((option) => option.text)).toContain('Custom show: Marathon'));
    const texts = [...(within(dialog).getByLabelText('Slot 1 source') as unknown as HTMLSelectElement).options].map((option) => option.text);
    expect(texts).toEqual(expect.arrayContaining(['Bravo Show', 'Movies', 'Custom show: Marathon', 'Filler list: Station Ads', 'Redirect to CH 7 Movie Night', 'Flex (open airtime)', 'Another show from the library…']));
    expect(texts).not.toContain('Redirect to CH 3 Newsroom');
  });

  it('adds a slot with commercials and saves its settings', async () => {
    const { requests } = fakeCompanion({ schedule });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('button', { name: 'Edit slot schedule…' }));
    const dialog = await screen.findByRole('dialog', { name: /Slot schedule ·/ });
    await waitFor(() => expect(within(within(dialog).getByLabelText('Add a slot')).getByRole('option', { name: 'Custom show: Marathon' })).toBeTruthy());
    fireEvent.change(within(dialog).getByLabelText('Add a slot'), { target: { value: `custom-show:${CUSTOM_ID}` } });
    expect(within(dialog).getByLabelText('Slot 3 source')).toBeTruthy();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Options for slot 3' }));
    fireEvent.click(within(dialog).getByRole('button', { name: 'Add commercials' }));
    fireEvent.click(within(dialog).getByLabelText('Mid-roll breaks inside programs'));
    fireEvent.click(within(within(dialog).getByRole('group', { name: 'Where commercial list 1 plays' })).getByLabelText('Mid-roll breaks'));
    fireEvent.change(within(dialog).getByDisplayValue('By weight'), { target: { value: 'none' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Preview lineup' }));
    fireEvent.click(within(await screen.findByRole('region', { name: 'Schedule preview' })).getByRole('button', { name: 'Save schedule' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    const body = requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!.body as { type: string; schedule: { settings: { randomDistribution: string }; slots: Array<Record<string, unknown>> } };
    expect(body.type).toBe('random');
    expect(body.schedule.settings.randomDistribution).toBe('none');
    expect(body.schedule.slots[2]).toMatchObject({ type: 'custom-show', customShowId: CUSTOM_ID, weight: 1, filler: [{ fillerListId: FILLER_ID, types: ['pre', 'mid'] }], midRoll: { maxBreaks: 3 } });
    expect(body.schedule.slots[2].id).toMatch(/^[0-9a-f-]{36}$/);
  });

  it('creates a slot schedule for a manual channel', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Channel' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Create Slot Schedule/ }));
    const dialog = await screen.findByRole('dialog', { name: /New slot schedule ·/ });
    fireEvent.click(within(dialog).getByRole('radio', { name: 'Time slots' }));
    await waitFor(() => expect(within(within(dialog).getByLabelText('Add a slot')).getByRole('option', { name: 'Movies' })).toBeTruthy());
    fireEvent.change(within(dialog).getByLabelText('Add a slot'), { target: { value: 'movie' } });
    fireEvent.change(within(dialog).getByLabelText('Slot 1 start'), { target: { value: '20:00:00' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Preview lineup' }));
    fireEvent.click(within(await screen.findByRole('region', { name: 'Schedule preview' })).getByRole('button', { name: 'Save schedule' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    const body = requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!.body as { type: string; schedule: { slots: Array<Record<string, unknown>> } };
    expect(body.type).toBe('time');
    expect(body.schedule.slots).toEqual([expect.objectContaining({ type: 'movie', startTime: 20 * 3_600_000 })]);
  });

  it('discards a preview with Back and leaves Tunarr untouched', async () => {
    const { requests } = fakeCompanion({ schedule });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('button', { name: 'Edit slot schedule…' }));
    fireEvent.click(within(await screen.findByRole('dialog', { name: /Slot schedule ·/ })).getByRole('button', { name: 'Preview lineup' }));
    await screen.findByRole('region', { name: 'Schedule preview' });
    fireEvent.keyDown(document.body, { key: 'Escape' });
    expect(screen.queryByRole('region', { name: 'Schedule preview' })).toBeNull();
    expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(0);
  });
});

describe('full lineup editing', () => {
  const posted = (requests: ReturnType<typeof fakeCompanion>['requests']) => (requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!.body as { lineup: LineupItem[] }).lineup;

  it('inserts programs from the library after the selection', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getByRole('button', { name: 'Insert…' }));
    const insert = await screen.findByRole('dialog', { name: 'Insert into the lineup' });
    fireEvent.click(within(insert).getByRole('button', { name: 'Browse library…' }));
    const library = await screen.findByRole('dialog', { name: 'Insert programs' });
    fireEvent.click(await within(library).findByRole('button', { name: 'Add Zulu Movie (1999)' }));
    fireEvent.click(within(library).getByRole('button', { name: 'Insert 1' }));
    expect(await screen.findByText(/^Inserted “Zulu Movie” at /)).toBeTruthy();
    expect(screen.getAllByText('Zulu Movie').length).toBeGreaterThan(0);
    // The channel has looped many times, so the movie airs later than the row
    // it went after; the desk follows it there and selects it.
    await waitFor(() => expect(document.querySelector('.program.cursor')?.textContent).toContain('Zulu Movie'));
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(posted(requests).slice(0, 2)).toEqual([mixedLineup()[0], { type: 'content', id: LIBRARY_MOVIE.uuid, duration: LIBRARY_MOVIE.duration }]);
  });

  it('inserts next to what is on air when the lineup’s first item airs on another day', async () => {
    // A cycle of about 11 days: item 0 aired yesterday, so it is not on screen.
    const lineup: LineupItem[] = [
      { type: 'content', id: 'prog-bravo', duration: 40 * 60_000 },
      { type: 'flex', duration: 12 * 3_600_000 },
      ...Array.from({ length: 48 }, () => ({ type: 'content', id: 'prog-alpha', duration: 30 * 60_000 })),
      { type: 'flex', duration: 10 * 24 * 3_600_000 },
    ];
    const startTime = dayRange(today()).from.getTime() - 12 * 3_600_000;
    const { requests } = fakeCompanion({ lineup, startTime });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('button', { name: 'Insert…' }));
    const insert = await screen.findByRole('dialog', { name: 'Insert into the lineup' });
    fireEvent.click(within(insert).getByRole('button', { name: 'Browse library…' }));
    const library = await screen.findByRole('dialog', { name: 'Insert programs' });
    fireEvent.click(await within(library).findByRole('button', { name: 'Add Zulu Movie (1999)' }));
    fireEvent.click(within(library).getByRole('button', { name: 'Insert 1' }));
    expect(await screen.findByText(/^Inserted “Zulu Movie” at /)).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    const saved = (requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!.body as { lineup: LineupItem[] }).lineup;
    expect(saved.findIndex((item) => item.id === LIBRARY_MOVIE.uuid)).toBe(lineupIndexAt(lineup, startTime, Date.now()) + 1);
  });

  const insertFromLibrary = async (choose?: (dialog: HTMLElement) => void) => {
    fireEvent.click(screen.getAllByRole('button', { name: 'Insert…' })[0]);
    const insert = await screen.findByRole('dialog', { name: 'Insert into the lineup' });
    choose?.(insert);
    fireEvent.click(within(insert).getByRole('button', { name: 'Browse library…' }));
    const library = await screen.findByRole('dialog', { name: 'Insert programs' });
    fireEvent.click(await within(library).findByRole('button', { name: 'Add Zulu Movie (1999)' }));
    fireEvent.click(within(library).getByRole('button', { name: 'Insert 1' }));
  };

  it('inserts at a date and time on another day, and shows where it starts first', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    const startTime = dayRange(today()).from.getTime() - 60 * 60_000;
    const day = new Date(dayRange(today()).from.getTime() + 3 * 86_400_000 + 12 * 3_600_000);
    const date = `${day.getFullYear()}-${String(day.getMonth() + 1).padStart(2, '0')}-${String(day.getDate()).padStart(2, '0')}`;
    await insertFromLibrary((dialog) => {
      expect(within(dialog).getByRole('status', { name: 'Insert placement' }).textContent).toMatch(/^Starts /);
      fireEvent.click(within(dialog).getByRole('radio', { name: 'At a time…' }));
      fireEvent.change(within(dialog).getByLabelText('Insert date'), { target: { value: date } });
      fireEvent.change(within(dialog).getByLabelText('Insert time'), { target: { value: '20:05' } });
      expect(within(dialog).getByRole('status', { name: 'Insert placement' }).textContent).toContain('Tunarr can’t cut a program short');
    });
    expect(await screen.findByText(/^Inserted “Zulu Movie” at /)).toBeTruthy();
    expect((screen.getByLabelText(/date/i, { selector: 'input[type=date]' }) as HTMLInputElement).value).toBe(date);
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    // In the saved (longer) lineup, the movie's first airing at or after 20:05
    // that day is the boundary right after 20:05: no later than the program
    // that was on then would end.
    const at = new Date(`${date}T20:05:00`).getTime();
    const saved = posted(requests);
    const cycle = saved.reduce((sum, item) => sum + item.duration, 0);
    const index = saved.findIndex((item) => item.id === LIBRARY_MOVIE.uuid);
    const offset = saved.slice(0, index).reduce((sum, item) => sum + item.duration, 0);
    const airs = startTime + offset + Math.ceil((at - startTime - offset) / cycle) * cycle;
    expect(airs).toBeGreaterThanOrEqual(at);
    expect(lineupIndexAt(saved, startTime, at)).toBe(index - 1);
    expect(airs - at).toBeLessThan(saved[index - 1].duration);
  });

  it('inserts into an empty channel', async () => {
    const { requests } = fakeCompanion({ lineup: [] });
    render(<Home />);
    expect(await screen.findByText('This lineup is empty.')).toBeTruthy();
    await insertFromLibrary((dialog) => {
      expect(within(dialog).getByRole('status', { name: 'Insert placement' }).textContent).toContain('becomes its first item');
      expect((within(dialog).getByRole('radio', { name: 'At a time…' }) as HTMLButtonElement).disabled).toBe(true);
    });
    fireEvent.click(await screen.findByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(posted(requests)).toEqual([{ type: 'content', id: LIBRARY_MOVIE.uuid, duration: LIBRARY_MOVIE.duration }]);
  });

  it('inserts into a channel generated from a slot schedule, after a warning', async () => {
    const { requests } = fakeCompanion({ schedule: { type: 'time', slots: [] } });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    await insertFromLibrary();
    fireEvent.click(await screen.findByRole('button', { name: 'Save lineup' }));
    fireEvent.click(within(await screen.findByRole('alertdialog')).getByRole('button', { name: 'Save manual lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(posted(requests).some((item) => item.id === LIBRARY_MOVIE.uuid)).toBe(true);
  });

  it('keeps what is on air in place when asked, and the companion moves the start time on save', async () => {
    // Started a day ago, so the 140-minute lineup has repeated whatever the time.
    const { requests, state } = fakeCompanion({ startTime: dayRange(today()).from.getTime() - 24 * 3_600_000 });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    const onAir = () => `${document.querySelector('.program.on-air time')?.textContent} ${document.querySelector('.program.on-air .title')?.textContent ?? ''}`;
    const before = onAir();
    fireEvent.click(document.querySelector('.program.on-air')!);
    fireEvent.click(screen.getAllByRole('button', { name: 'Insert…' })[0]);
    const insert = await screen.findByRole('dialog', { name: 'Insert into the lineup' });
    fireEvent.click(within(insert).getByRole('radio', { name: 'Flex time' }));
    // The channel has repeated many times: without the option, programs around the insert move.
    expect(within(insert).getByRole('status', { name: 'Insert placement' }).textContent).toContain('has played through');
    fireEvent.click(within(insert).getByLabelText(/Keep what’s on air in place/));
    expect(within(insert).getByRole('status', { name: 'Insert placement' }).textContent).not.toContain('has played through');
    fireEvent.click(within(insert).getByRole('button', { name: 'Insert' }));
    expect(await screen.findByText(/^Inserted flex time at /)).toBeTruthy();
    // Inserted right after what's on air, which keeps its time.
    expect(onAir()).toBe(before);
    expect((screen.getByLabelText(/Keep what’s on air in place/) as HTMLInputElement).checked).toBe(true);
    await waitFor(async () => expect((await draftStore().get('chan-news'))?.keepOnAir).toBe(true));

    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect((requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!.body as { keepOnAir?: boolean }).keepOnAir).toBe(true);
    expect(await screen.findByText(/start time moved so what’s on air keeps its time/)).toBeTruthy();
    expect(state.lineup.some((item) => item.type === 'flex' && item.duration === 2 * 60_000)).toBe(true);
    // Saved and reloaded from the moved start time, what's on air is still where it was.
    await waitFor(() => expect(onAir()).toBe(before));
  });

  it('lists what is picked before inserting, and names it in the edit list', async () => {
    fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getAllByRole('button', { name: 'Insert…' })[0]);
    fireEvent.click(within(await screen.findByRole('dialog', { name: 'Insert into the lineup' })).getByRole('button', { name: 'Browse library…' }));
    const library = await screen.findByRole('dialog', { name: 'Insert programs' });
    fireEvent.click(await within(library).findByRole('button', { name: 'Add Zulu Movie (1999)' }));
    const picked = within(library).getByRole('list', { name: 'Selected programs' });
    expect(within(picked).getByText('Zulu Movie (1999)')).toBeTruthy();
    // A wrong pick can be taken out before anything is inserted.
    fireEvent.click(within(picked).getByRole('button', { name: 'Remove Zulu Movie (1999)' }));
    expect(within(library).queryByRole('list', { name: 'Selected programs' })).toBeNull();
    expect((within(library).getByRole('button', { name: /^Insert/ }) as HTMLButtonElement).disabled).toBe(true);
    fireEvent.click(within(library).getByRole('button', { name: 'Add Zulu Movie (1999)' }));
    fireEvent.click(within(library).getByRole('button', { name: 'Insert 1' }));
    expect(await screen.findByText(/^Inserted “Zulu Movie” at /)).toBeTruthy();
  });

  it('lists a whole library in episode order and finds an episode by number in any language', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.click(screen.getAllByRole('button', { name: 'Insert…' })[0]);
    fireEvent.click(within(await screen.findByRole('dialog', { name: 'Insert into the lineup' })).getByRole('button', { name: 'Browse library…' }));
    const library = await screen.findByRole('dialog', { name: 'Insert programs' });
    fireEvent.change(within(library).getByLabelText('Library'), { target: { value: 'lib-videos' } });
    // Both pages are loaded, then shown 1, 2, 3… whichever language each title is in.
    await waitFor(() => expect(within(library).getByText('153 items')).toBeTruthy());
    expect(requests.filter((r) => r.path === '/api/tunarr/library/search' && (r.body as { libraryId?: string }).libraryId === 'lib-videos').map((r) => (r.body as { page: number }).page)).toEqual([0, 1]);
    expect((within(library).getByLabelText('Order') as unknown as HTMLSelectElement).value).toBe('number');
    const titles = () => [...library.querySelectorAll('.library-item b')].map((element) => element.textContent);
    expect(titles().slice(0, 3)).toEqual(['Capítulo 1 - Viudas e Hijos del Rock & Roll', 'Chapter 2 - Widows and Children of Rock & Roll', 'Capítulo 3 - Viudas e Hijos del Rock & Roll']);
    // "capitulo 2" finds episode 2 although its title is in English, and not Capítulo 20-29.
    fireEvent.change(within(library).getByLabelText('Search the library'), { target: { value: 'capitulo 2' } });
    expect(titles()).toEqual(['Chapter 2 - Widows and Children of Rock & Roll']);
    expect(within(library).getByText('1 of 153')).toBeTruthy();
    fireEvent.click(within(library).getByRole('button', { name: 'Add Chapter 2 - Widows and Children of Rock & Roll' }));
    fireEvent.click(within(library).getByRole('button', { name: 'Insert 1' }));
    expect(await screen.findByText(/^Inserted “Chapter 2 - Widows and Children of Rock & Roll” at /)).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(posted(requests).some((item) => item.id === SERIES[1].uuid)).toBe(true);
    // Searching never went to Tunarr: the whole list was already here.
    expect(requests.some((r) => r.path === '/api/tunarr/library/search' && (r.body as { text?: string }).text)).toBe(false);
  });

  it('inserts a commercial break that plays from filler lists', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await pickAlpha();
    fireEvent.keyDown(document.body, { key: 'i' });
    const insert = await screen.findByRole('dialog', { name: 'Insert into the lineup' });
    fireEvent.click(within(insert).getByRole('radio', { name: 'Commercial break' }));
    // "Station Ads" reads as a commercials list, so it is picked already.
    await waitFor(() => expect((within(insert).getByLabelText(/Station Ads/) as HTMLInputElement).checked).toBe(true));
    expect(within(insert).getByText(/Tag a filler list as Station IDs/)).toBeTruthy();
    fireEvent.change(within(insert).getByLabelText('Length minutes'), { target: { value: '3' } });
    fireEvent.click(within(insert).getByRole('radio', { name: /Before/ }));
    fireEvent.click(within(insert).getByRole('button', { name: 'Insert' }));
    expect(await screen.findByText(/^Inserted a commercial break at /)).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(posted(requests)[0]).toEqual({ type: 'flex', duration: 3 * 60_000, fillerConfig: { fillerListIds: [FILLER_ID], fillerRepeatCooldownMs: 0, origin: 'flex' } });
  });

  it('removes with Delete, changes a flex length, and undoes', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    // The fixture's flex entry plays from filler lists, so it is shown as a commercial break.
    const flexRow = [...document.querySelectorAll<HTMLButtonElement>('.program')].find((row) => row.textContent?.includes('Commercial break'))!;
    fireEvent.click(flexRow);
    fireEvent.change(screen.getByLabelText('Length minutes'), { target: { value: '25' } });
    fireEvent.click(screen.getByRole('button', { name: 'Apply' }));
    expect(screen.getByText('Changed “Commercial break” to 0:25:00')).toBeTruthy();
    const alpha = [...document.querySelectorAll<HTMLButtonElement>('.program')].find((row) => row.textContent?.includes('Alpha Movie'))!;
    fireEvent.click(alpha);
    fireEvent.keyDown(alpha, { key: 'Delete' });
    expect(screen.getByText('Removed “Alpha Movie”')).toBeTruthy();
    fireEvent.click(screen.getAllByRole('button', { name: 'Undo' })[0]);
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(posted(requests).map((item) => [item.type, item.duration])).toEqual(mixedLineup().map((item) => [item.type, item.type === 'flex' ? 25 * 60_000 : item.duration]));
  });

  it('keeps inserted programs, with their titles, in a draft across a reload', async () => {
    fakeCompanion();
    const first = render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('button', { name: 'Insert…' }));
    fireEvent.click(within(await screen.findByRole('dialog', { name: 'Insert into the lineup' })).getByRole('button', { name: 'Browse library…' }));
    const library = await screen.findByRole('dialog', { name: 'Insert programs' });
    fireEvent.click(await within(library).findByRole('button', { name: 'Add Zulu Movie (1999)' }));
    fireEvent.click(within(library).getByRole('button', { name: 'Insert 1' }));
    await waitFor(async () => expect((await draftStore().get('chan-news'))?.extras).toHaveLength(1));
    first.unmount();
    render(<Home />);
    expect(await screen.findByText(/Restored your unsaved changes/)).toBeTruthy();
    expect(screen.getAllByText('Zulu Movie').length).toBeGreaterThan(0);
  });
});

describe('lists and channel settings', () => {
  it('creates a filler list from library programs', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Lists' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Filler Lists/ }));
    const manager = await screen.findByRole('dialog', { name: /Filler lists/ });
    expect(await within(manager).findByText('Station Ads')).toBeTruthy();
    fireEvent.click(within(manager).getByRole('button', { name: 'New filler list' }));
    fireEvent.change(within(manager).getByLabelText('List name'), { target: { value: 'Bumpers' } });
    fireEvent.click(within(manager).getByRole('button', { name: 'Add programs…' }));
    const library = await screen.findByRole('dialog', { name: 'Add to Bumpers' });
    fireEvent.click(await within(library).findByRole('button', { name: 'Add Zulu Movie (1999)' }));
    fireEvent.click(within(library).getByRole('button', { name: 'Add 1' }));
    fireEvent.click(within(manager).getByRole('button', { name: 'Create filler list' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/filler-lists')).toBe(1));
    expect(requests.find((r) => r.method === 'POST' && r.path === '/api/tunarr/filler-lists')!.body).toEqual({ name: 'Bumpers', programs: [{ type: 'content', id: LIBRARY_MOVIE.uuid, duration: LIBRARY_MOVIE.duration, program: LIBRARY_MOVIE }] });
    expect(await within(manager).findByText('Bumpers', { selector: 'b' })).toBeTruthy();
  });

  it('adds channel-wide commercials for flex time', async () => {
    const { requests, state } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Channel' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Channel Settings/ }));
    const dialog = await screen.findByRole('dialog', { name: 'Channel settings' });
    fireEvent.click(await within(dialog).findByRole('tab', { name: 'Commercials' }));
    fireEvent.click(await within(dialog).findByRole('button', { name: 'Add filler list' }));
    fireEvent.change(within(dialog).getByLabelText('Filler list 1 weight'), { target: { value: '5' } });
    fireEvent.change(within(dialog).getByLabelText('Filler list 1 cooldown minutes'), { target: { value: '10' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Save settings' }));
    await waitFor(() => expect(count(requests, 'PUT', '/api/tunarr/channels/chan-news/settings')).toBe(1));
    expect(requests.find((r) => r.method === 'PUT')!.body).toEqual({ fillerCollections: [{ id: FILLER_ID, weight: 5, cooldownSeconds: 600 }] });
    expect(state.settings.fillerCollections).toHaveLength(1);
    expect(await screen.findByText('Channel settings saved to Tunarr')).toBeTruthy();
  });
});

describe('channels and Tunarr setup', () => {
  it('shows channel logos in the rail, and the number when a channel has none', async () => {
    fakeCompanion();
    const { container } = render(<Home />);
    await screen.findAllByText('Alpha Movie');
    const logo = container.querySelector('.channel-rail .channel-logo img') as HTMLImageElement;
    expect(logo.getAttribute('src')).toMatch(/^\/api\/tunarr\/channels\/chan-movies\/logo\?v=[a-z0-9]+$/);
    // Tunarr's own address never reaches the page.
    expect(container.innerHTML).not.toContain('host.docker.internal');
    expect(container.querySelector('.channel-rail .no-logo')!.textContent).toBe('3');
    fireEvent.error(logo);
    await waitFor(() => expect(container.querySelectorAll('.channel-rail .no-logo')).toHaveLength(2));
  });

  it('creates a channel and switches to it', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Channel' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /New Channel/ }));
    const dialog = await screen.findByRole('dialog', { name: 'New channel' });
    expect((within(dialog).getByLabelText('Channel number') as HTMLInputElement).value).toBe('8');
    fireEvent.change(within(dialog).getByLabelText('Channel name'), { target: { value: 'Late Show' } });
    await within(dialog).findByRole('option', { name: 'Default (default)' });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Create channel' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/create')).toBe(1));
    expect(requests.find((r) => r.path === '/api/tunarr/channels/create')!.body).toEqual({ name: 'Late Show', number: 8, groupTitle: 'tunarr', transcodeConfigId: PROFILE_ID });
    await waitFor(() => expect(requests.some((r) => r.path === '/api/tunarr/channels/chan-new/programming')).toBe(true));
    expect(await screen.findByText('Channel created in Tunarr')).toBeTruthy();
  });

  it('deletes a channel only after confirming', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Channel' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Delete Channel/ }));
    const confirm = await screen.findByRole('alertdialog', { name: 'Delete CH 3 Newsroom?' });
    expect(count(requests, 'DELETE', '/api/tunarr/channels/chan-news')).toBe(0);
    fireEvent.click(within(confirm).getByRole('button', { name: 'Delete channel' }));
    await waitFor(() => expect(count(requests, 'DELETE', '/api/tunarr/channels/chan-news')).toBe(1));
    expect(await screen.findByText('Deleted CH 3 Newsroom')).toBeTruthy();
    await waitFor(() => expect(screen.queryByRole('button', { name: /Newsroom/ })).toBeNull());
  });

  it('changes streaming settings and the transcode profile', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Channel' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Channel Settings/ }));
    const dialog = await screen.findByRole('dialog', { name: 'Channel settings' });
    fireEvent.click(await within(dialog).findByRole('tab', { name: 'Streaming' }));
    fireEvent.change(within(dialog).getByLabelText('Stream format'), { target: { value: 'mpegts' } });
    await within(dialog).findByRole('option', { name: /Light/ });
    fireEvent.change(within(dialog).getByLabelText('Transcode profile'), { target: { value: PROFILE_720 } });
    fireEvent.click(within(dialog).getByRole('tab', { name: 'Logo & watermark' }));
    fireEvent.change(within(dialog).getByLabelText('Logo image address'), { target: { value: 'https://example.com/news.png' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Save settings' }));
    await waitFor(() => expect(count(requests, 'PUT', '/api/tunarr/channels/chan-news/settings')).toBe(1));
    expect(requests.find((r) => r.method === 'PUT')!.body).toEqual({ streamMode: 'mpegts', transcodeConfigId: PROFILE_720, icon: { path: 'https://example.com/news.png' } });
  });

  it('builds a smart collection from rules and previews it', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Lists' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Smart Collections/ }));
    const dialog = await screen.findByRole('dialog', { name: 'Smart collections' });
    fireEvent.click(within(dialog).getByRole('button', { name: 'New smart collection' }));
    fireEvent.change(within(dialog).getByLabelText('Collection name'), { target: { value: '90s comedies' } });
    fireEvent.change(within(dialog).getByLabelText('Rule 1 value'), { target: { value: 'Comedy, Family' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Add rule' }));
    fireEvent.change(within(dialog).getByLabelText('Rule 2 field'), { target: { value: 'year' } });
    fireEvent.change(within(dialog).getByLabelText('Rule 2 comparison'), { target: { value: 'between' } });
    fireEvent.change(within(dialog).getByLabelText('Rule 2 value'), { target: { value: '1990' } });
    fireEvent.change(within(dialog).getByLabelText('Rule 2 upper value'), { target: { value: '1999' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Preview matches' }));
    expect(await within(dialog).findByText('12 matches')).toBeTruthy();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Create collection' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/smart-collections/create')).toBe(1));
    expect(requests.find((r) => r.path === '/api/tunarr/smart-collections/create')!.body).toEqual({
      name: '90s comedies', keywords: '', match: 'all', rules: [{ field: 'genre', op: 'is', values: ['Comedy', 'Family'] }, { field: 'year', op: 'between', value: 1990, value2: 1999 }],
    });
  });

  it('adds a Plex media source and turns libraries on', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Setup' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Media Sources/ }));
    const dialog = await screen.findByRole('dialog', { name: 'Media sources' });
    expect(await within(dialog).findByLabelText('Use library Movies')).toBeTruthy();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Add media source…' }));
    fireEvent.change(within(dialog).getByLabelText('Source name'), { target: { value: 'Den Plex' } });
    fireEvent.change(within(dialog).getByLabelText('Server address'), { target: { value: 'http://192.168.1.20:32400' } });
    fireEvent.change(within(dialog).getByLabelText('Plex token'), { target: { value: 'abcdef123456' } });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Add source' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/media-sources/add')).toBe(1));
    expect(requests.find((r) => r.path === '/api/tunarr/media-sources/add')!.body).toEqual({ type: 'plex', name: 'Den Plex', uri: 'http://192.168.1.20:32400', accessToken: 'abcdef123456' });
    expect(await within(dialog).findByText('Den Plex')).toBeTruthy();
  });
});

describe('season filters and linked slots', () => {
  const schedule = {
    type: 'random',
    randomDistribution: 'uniform',
    slots: [
      { id: 'a1000000-0000-4000-8000-000000000001', type: 'show', showId: 'show-1', show: { title: 'Bravo Show', mediaSourceId: 'src-1', libraryId: 'lib-tv' }, order: 'next', direction: 'asc', weight: 1, cooldownMs: 0, seasonFilter: [], seasonExcludeFilter: [] },
      { id: 'b1000000-0000-4000-8000-000000000002', type: 'show', showId: 'show-1', show: { title: 'Bravo Show' }, order: 'shuffle', direction: 'asc', weight: 1, cooldownMs: 0, seasonFilter: [], seasonExcludeFilter: [] },
    ],
  };

  it('limits a show slot to some seasons and links two slots of the same show', async () => {
    const { requests } = fakeCompanion({ schedule });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('button', { name: 'Edit slot schedule…' }));
    const dialog = await screen.findByRole('dialog', { name: /Slot schedule ·/ });
    fireEvent.click(within(dialog).getByRole('button', { name: 'Options for slot 1' }));
    fireEvent.change(within(dialog).getByLabelText('Which seasons'), { target: { value: 'only' } });
    const seasons = within(dialog).getByRole('group', { name: 'Seasons' });
    fireEvent.click(await within(seasons).findByLabelText(/Season 2/));
    expect(requests.find((r) => r.path === '/api/tunarr/library/search')!.body).toMatchObject({ mediaSourceId: 'src-1', libraryId: 'lib-tv', type: 'season', parentId: 'show-1' });
    fireEvent.change(within(dialog).getByLabelText('Slot 1 shares episodes with'), { target: { value: '1' } });
    expect(within(dialog).getByText(/Group 1: slots 1, 2 move through one episode list together/)).toBeTruthy();
    // Random-slot groups always continue, so there's no rerun choice here.
    expect(within(dialog).queryByLabelText('Slot 1 link mode')).toBeNull();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Preview lineup' }));
    fireEvent.click(within(await screen.findByRole('region', { name: 'Schedule preview' })).getByRole('button', { name: 'Save schedule' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    const slots = (requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!.body as { schedule: { slots: Array<Record<string, unknown>> } }).schedule.slots;
    expect(slots[0]).toMatchObject({ seasonFilter: [2], seasonExcludeFilter: [], linkMode: 'continue' });
    expect(slots[0].iterationGroup).toBe(slots[1].iterationGroup);
    expect(slots[0].iterationGroup).toMatch(/^[0-9a-f-]{36}$/);
    // Linking copies the group's play order to the joining slot.
    expect(slots[0].order).toBe('shuffle');
  });
});

describe('programming templates', () => {
  it('fills a template’s roles with suggested smart collections and opens it as a weekly time-slot draft', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Channel' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Programming Templates/ }));
    const dialog = await screen.findByRole('dialog', { name: 'Programming templates' });
    fireEvent.change(within(dialog).getByLabelText('Template group'), { target: { value: 'Japan' } });
    fireEvent.click(within(dialog).getByRole('option', { name: /NHK General TV/ }));
    expect(within(dialog).getByText(/Inspired by NHK General TV programming\. Weekly schedule/)).toBeTruthy();
    // Suggestions with matches are picked by default.
    await waitFor(() => expect((within(dialog).getByLabelText('Morning drama source') as unknown as HTMLSelectElement).value).toBe('__suggest__'));
    fireEvent.change(within(dialog).getByLabelText('Culture & music source'), { target: { value: '' } });
    fireEvent.change(within(dialog).getByLabelText('Promos list'), { target: { value: FILLER_ID } });
    fireEvent.click(within(dialog).getByRole('button', { name: /Create 5 smart collections and open the schedule/ }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/smart-collections/create')).toBe(5));
    expect(requests.find((r) => r.path === '/api/tunarr/smart-collections/create')!.body).toMatchObject({ name: 'NHK General TV · News', match: 'all' });
    const editor = await screen.findByRole('dialog', { name: /New slot schedule ·/ });
    expect(within(editor).getByText(/Time slots, repeating every week/)).toBeTruthy();
    expect((within(editor).getByLabelText('Slot 1 day') as unknown as HTMLSelectElement).selectedOptions[0].text).toBe('Sunday');
    // Nothing is saved until the schedule is previewed and saved.
    expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(0);
  });
});

describe('AI programming, saved templates and events', () => {
  const openTemplates = async () => {
    fireEvent.click(screen.getByRole('menuitem', { name: 'Channel' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Programming Templates/ }));
    return screen.findByRole('dialog', { name: 'Programming templates' });
  };

  it('writes a schedule with AI, saves it to My templates and opens it', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    const dialog = await openTemplates();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Ask AI…' }));
    expect(await within(dialog).findByText(/Uses Anthropic \(claude-sonnet-5-5\)/)).toBeTruthy();
    fireEvent.click(within(dialog).getByRole('button', { name: /90s Saturday-morning cartoon/ }));
    fireEvent.click(within(dialog).getByRole('button', { name: 'Write the schedule' }));
    expect(await within(dialog).findByText('Your library has no live-action kids shows.')).toBeTruthy();
    expect(requests.find((r) => r.path === '/api/tunarr/ai/template')!.body).toEqual({ prompt: 'A 90s Saturday-morning cartoon channel with toy commercials between shows', channelId: 'chan-news', includeLibrary: true });
    // The AI's show is the role's default, and its commercials list is preselected.
    expect((within(dialog).getByLabelText('Cartoons source') as unknown as HTMLSelectElement).selectedOptions[0].text).toBe('Bravo Show');
    expect((within(dialog).getByLabelText('Commercials list') as unknown as HTMLSelectElement).value).toBe(FILLER_ID);
    fireEvent.click(within(dialog).getByRole('button', { name: 'Save to My templates' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/templates')).toBe(1));
    expect(requests.find((r) => r.method === 'POST' && r.path === '/api/tunarr/templates')!.body).toMatchObject({ name: 'AI Saturday cartoons', defaults: { cartoons: { key: 'show:show-1' } } });
    expect(await within(dialog).findByText(/Saved “AI Saturday cartoons” to My templates/)).toBeTruthy();
    fireEvent.click(within(dialog).getByRole('button', { name: 'Open the schedule' }));
    const editor = await screen.findByRole('dialog', { name: /New slot schedule ·/ });
    expect(within(editor).getByText(/Time slots, repeating every day · 2 slots/)).toBeTruthy();
  });

  it('builds a template in the editor with per-block ad levels', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    const dialog = await openTemplates();
    fireEvent.click(within(dialog).getByRole('button', { name: 'New template' }));
    const editor = await screen.findByRole('dialog', { name: 'New template' });
    fireEvent.change(within(editor).getByLabelText('Template name'), { target: { value: 'My station' } });
    fireEvent.change(within(editor).getByLabelText('Day plan type'), { target: { value: 'weekly' } });
    fireEvent.click(within(editor).getByRole('tab', { name: 'Saturday' }));
    fireEvent.change(within(editor).getByLabelText('Block 2 ads'), { target: { value: 'none' } });
    fireEvent.click(within(editor).getByRole('button', { name: 'Save template' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/templates')).toBe(1));
    const saved = requests.find((r) => r.method === 'POST' && r.path === '/api/tunarr/templates')!.body as { name: string; days: Record<string, unknown> };
    expect(saved.name).toBe('My station');
    expect(saved.days).toEqual({ weekdays: [['06:00', 'news'], ['20:00', 'drama', 'heavy']], saturday: [['06:00', 'news'], ['20:00', 'drama', 'none']], sunday: [['06:00', 'news'], ['20:00', 'drama', 'heavy']] });
  });

  it('schedules an event on a date, replacing what was on', async () => {
    fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    fireEvent.click(screen.getByRole('menuitem', { name: 'Edit' }));
    fireEvent.click(screen.getByRole('menuitem', { name: /Schedule Event/ }));
    const dialog = await screen.findByRole('dialog', { name: 'Schedule an event' });
    fireEvent.change(within(dialog).getByLabelText('What airs'), { target: { value: 'redirect' } });
    fireEvent.change(within(dialog).getByLabelText('Event length minutes'), { target: { value: '45' } });
    fireEvent.change(within(dialog).getByLabelText('Event name'), { target: { value: 'Cup final' } });
    const preview = within(dialog).getByRole('status', { name: 'Event placement' });
    expect(preview.textContent).toMatch(/Cup final: /);
    expect(preview.textContent).toMatch(/This lineup repeats every 2\.3 hours/);
    fireEvent.click(within(dialog).getByRole('button', { name: 'Place event' }));
    expect(await screen.findByText(/Scheduled “Cup final” for/)).toBeTruthy();
    expect(screen.getAllByText(/Movie Night/).length).toBeGreaterThan(0);
  });
});

describe('station IDs, commercials and flex time', () => {
  const posted = (requests: ReturnType<typeof fakeCompanion>['requests']) => (requests.find((r) => r.method === 'POST' && r.path.endsWith('/programming'))!.body as { lineup: LineupItem[] }).lineup;
  const menu = (title: string, item: RegExp) => {
    fireEvent.click(screen.getByRole('menuitem', { name: title }));
    fireEvent.click(screen.getByRole('menuitem', { name: item }));
  };

  it('marks breaks, filler and redirects in the day view and expands a break rundown', async () => {
    fakeCompanion({ stationIds: true });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    expect(document.querySelector('.program.kind-break .kind-badge')?.textContent).toBe('BREAK');
    expect(document.querySelector('.program.kind-redirect')).toBeTruthy();
    expect(document.querySelector('.program.kind-program')).toBeTruthy();
    expect(document.querySelector('.hour-log')).toBeTruthy();
    expect(screen.queryByRole('list', { name: 'Estimated break rundown' })).toBeNull();
    fireEvent.keyDown(document.body, { key: 'b' });
    const rundowns = await screen.findAllByRole('list', { name: 'Estimated break rundown' });
    expect(within(rundowns[0]).getByText(/Tunarr picks the spots/)).toBeTruthy();
    fireEvent.keyDown(document.body, { key: 'b' });
    expect(screen.queryByRole('list', { name: 'Estimated break rundown' })).toBeNull();
  });

  it('tags a filler list as station IDs from Lists → Station IDs…', async () => {
    const { requests } = fakeCompanion();
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    menu('Lists', /^Station IDs/);
    const dialog = await screen.findByRole('dialog', { name: 'Station IDs' });
    expect(within(dialog).getByRole('radio', { name: 'Station IDs' }).getAttribute('aria-checked')).toBe('true');
    expect(within(dialog).getByText(/No lists tagged Station IDs yet/)).toBeTruthy();
    fireEvent.click(within(dialog).getByRole('radio', { name: 'All' }));
    fireEvent.click(await within(dialog).findByRole('option', { name: /Station Ads/ }));
    expect(await within(dialog).findByText(/1 spot ·/)).toBeTruthy();
    expect(within(dialog).getByText(':30 spot')).toBeTruthy();
    fireEvent.change(within(dialog).getByLabelText('On-air role'), { target: { value: 'station-id' } });
    await waitFor(() => expect(requests.some((r) => r.method === 'PUT' && r.path === `/api/tunarr/filler-roles/${FILLER_ID}`)).toBe(true));
    expect(requests.find((r) => r.method === 'PUT' && r.path.startsWith('/api/tunarr/filler-roles/'))!.body).toEqual({ role: 'station-id' });
  });

  it('inserts a commercial break that opens with a rotating station ID', async () => {
    const { requests } = fakeCompanion({ stationIds: true });
    render(<Home />);
    await pickAlpha();
    fireEvent.keyDown(document.body, { key: 'i' });
    const insert = await screen.findByRole('dialog', { name: 'Insert into the lineup' });
    fireEvent.click(within(insert).getByRole('radio', { name: 'Commercial break' }));
    const withId = await within(insert).findByLabelText(/Open with a station ID/) as HTMLInputElement;
    expect(withId.checked).toBe(true);
    fireEvent.change(within(insert).getByLabelText('Length minutes'), { target: { value: '2' } });
    fireEvent.click(within(insert).getByRole('button', { name: 'Insert' }));
    expect(await screen.findByText(/^Inserted a commercial break with a station ID at /)).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    const lineup = posted(requests);
    expect(lineup[1]).toEqual({ type: 'content', id: IDENT_A, duration: 10_000 });
    expect(lineup[2]).toMatchObject({ type: 'flex', duration: 2 * 60_000 - 10_000, fillerConfig: { fillerListIds: [FILLER_ID] } });
  });

  it('opens every existing break with a station ID in one undoable edit', async () => {
    const { requests } = fakeCompanion({ stationIds: true });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    await waitFor(() => expect(requests.some((r) => r.path === `/api/tunarr/filler-lists/${ID_LIST}/programs`)).toBe(true));
    await new Promise((resolve) => setTimeout(resolve, 0));
    menu('Edit', /^Open Breaks With Station IDs/);
    expect(await screen.findByText(/^Opened 1 break with a station ID/)).toBeTruthy();
    expect(document.querySelector('.program.kind-station-id')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    const lineup = posted(requests);
    expect(lineup[1]).toEqual({ type: 'content', id: IDENT_A, duration: 10_000 });
    // The break keeps its other fields and gives up the ID's length, so later programs keep their times.
    expect(lineup[2]).toEqual({ type: 'flex', duration: 10 * 60_000 - 10_000, persisted: true, fillerConfig: { fillerListIds: ['8f3c1b2a-0000-4000-8000-000000000001'], origin: 'flex' } });
    expect(lineup).toHaveLength(7);
  });

  it('opens breaks with the channel’s own station IDs when it has some', async () => {
    const { requests } = fakeCompanion({ stationIds: true, ownStationIds: true });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    await waitFor(() => expect(requests.some((r) => r.path === `/api/tunarr/filler-lists/${OWN_ID_LIST}/programs`)).toBe(true));
    await waitFor(() => expect(requests.some((r) => r.method === 'GET' && r.path === '/api/tunarr/channels/chan-news/settings')).toBe(true));
    await new Promise((resolve) => setTimeout(resolve, 0));
    menu('Edit', /^Open Breaks With Station IDs/);
    expect(await screen.findByText(/^Opened 1 break with this channel’s station IDs/)).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    // Not IDENT_A, which the shared pool would pick first.
    expect(posted(requests)[1]).toEqual({ type: 'content', id: IDENT_C, duration: 5_000 });
  });

  it('inserts the channel’s own station ID, named for it, from Insert → Station ID', async () => {
    const { requests } = fakeCompanion({ stationIds: true, namedIds: true });
    render(<Home />);
    await pickAlpha();
    await waitFor(() => expect(requests.some((r) => r.path === `/api/tunarr/filler-lists/${ID_LIST}/programs`)).toBe(true));
    await new Promise((resolve) => setTimeout(resolve, 0));
    fireEvent.keyDown(document.body, { key: 'i' });
    const insert = await screen.findByRole('dialog', { name: 'Insert into the lineup' });
    fireEvent.click(within(insert).getByRole('radio', { name: 'Station ID' }));
    const ids = within(insert).getByRole('radiogroup', { name: 'Station ID to insert' });
    // Only Newsroom's: not Movie Night's, and not the generic idents.
    expect(within(ids).getAllByRole('radio')).toHaveLength(1);
    expect(within(ids).getByLabelText(/NEWSROOM ID v2/)).toHaveProperty('checked', true);
    fireEvent.click(within(insert).getByRole('button', { name: 'Insert' }));
    expect(await screen.findByText(/^Inserted the station ID “NEWSROOM ID v2”/)).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'Save lineup' }));
    await waitFor(() => expect(count(requests, 'POST', '/api/tunarr/channels/chan-news/programming')).toBe(1));
    expect(posted(requests)[1]).toEqual({ type: 'content', id: NEWS_ID, duration: 12_000 });
  });

  it('assigns station IDs to a channel in Channel Settings', async () => {
    const { requests, state } = fakeCompanion({ stationIds: true });
    render(<Home />);
    await screen.findAllByText('Alpha Movie');
    menu('Channel', /^Channel Settings/);
    const dialog = await screen.findByRole('dialog', { name: /Channel settings/ });
    fireEvent.click(await within(dialog).findByRole('tab', { name: 'Commercials' }));
    const ids = within(dialog).getByRole('group', { name: 'This channel’s station IDs' });
    const box = within(ids).getByLabelText(/Channel 3 idents/) as HTMLInputElement;
    expect(box.checked).toBe(false);
    fireEvent.click(box);
    // It joins the channel's filler, where Tunarr airs it too.
    expect(within(dialog).getByLabelText('Filler list 1')).toHaveProperty('value', ID_LIST);
    fireEvent.click(within(dialog).getByRole('button', { name: 'Save settings' }));
    await waitFor(() => expect(count(requests, 'PUT', '/api/tunarr/channels/chan-news/settings')).toBe(1));
    expect(state.settings.fillerCollections).toEqual([{ id: ID_LIST, weight: 1, cooldownSeconds: 0 }]);
  });
});
